#include "../util/led_control.h"
#include "../config.h"

#include <avr/io.h>
#include <util/delay.h>
#include <avr/interrupt.h>


void run_startup_animation() {
    clear_led_brightness();
    update_pwm_pattern();
    run_pwm_cycle();
    

    const uint8_t brightness_sequence[] = {
        0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
        value_to_pwm_level(5., 5),
        value_to_pwm_level(4., 5),
        value_to_pwm_level(3., 5),
        value_to_pwm_level(2., 5),
        value_to_pwm_level(1., 5),
    };
    
    uint8_t pwm_val;
    for (uint8_t i=0; i<sizeof(brightness_sequence); i++) {
        /* autogenerated code from led_animation_layout.ipynb */
        pwm_val = brightness_sequence[(i + 15) % sizeof(brightness_sequence)];
        set_led_brightness(8, 3, pwm_val);
        run_pwm_cycle();
        pwm_val = brightness_sequence[(i + 14) % sizeof(brightness_sequence)];
        set_led_brightness(8, 4, pwm_val);
        pwm_val = brightness_sequence[(i + 13) % sizeof(brightness_sequence)];
        set_led_brightness(2, 6, pwm_val);
        set_led_brightness(8, 5, pwm_val);
        set_led_brightness(8, 6, pwm_val);
        pwm_val = brightness_sequence[(i + 12) % sizeof(brightness_sequence)];
        set_led_brightness(3, 5, pwm_val);
        set_led_brightness(1, 7, pwm_val);
        set_led_brightness(5, 0, pwm_val);
        set_led_brightness(8, 7, pwm_val);
        set_led_brightness(8, 8, pwm_val);
        set_led_brightness(8, 1, pwm_val);
        pwm_val = brightness_sequence[(i + 11) % sizeof(brightness_sequence)];
        set_led_brightness(4, 4, pwm_val);
        set_led_brightness(2, 5, pwm_val);
        set_led_brightness(1, 6, pwm_val);
        set_led_brightness(0, 7, pwm_val);
        set_led_brightness(6, 0, pwm_val);
        set_led_brightness(7, 0, pwm_val);
        pwm_val = brightness_sequence[(i + 10) % sizeof(brightness_sequence)];
        set_led_brightness(3, 4, pwm_val);
        set_led_brightness(1, 5, pwm_val);
        set_led_brightness(0, 6, pwm_val);
        set_led_brightness(4, 6, pwm_val);
        set_led_brightness(4, 7, pwm_val);
        set_led_brightness(5, 3, pwm_val);
        set_led_brightness(6, 1, pwm_val);
        set_led_brightness(6, 2, pwm_val);
        set_led_brightness(7, 1, pwm_val);
        run_pwm_cycle();
        pwm_val = brightness_sequence[(i + 9) % sizeof(brightness_sequence)];
        set_led_brightness(2, 4, pwm_val);
        set_led_brightness(4, 3, pwm_val);
        set_led_brightness(3, 7, pwm_val);
        set_led_brightness(5, 2, pwm_val);
        set_led_brightness(6, 3, pwm_val);
        set_led_brightness(7, 2, pwm_val);
        pwm_val = brightness_sequence[(i + 8) % sizeof(brightness_sequence)];
        set_led_brightness(3, 3, pwm_val);
        set_led_brightness(0, 5, pwm_val);
        set_led_brightness(4, 5, pwm_val);
        set_led_brightness(3, 6, pwm_val);
        set_led_brightness(2, 7, pwm_val);
        set_led_brightness(5, 1, pwm_val);
        set_led_brightness(5, 5, pwm_val);
        set_led_brightness(5, 6, pwm_val);
        set_led_brightness(6, 4, pwm_val);
        set_led_brightness(6, 5, pwm_val);
        set_led_brightness(7, 3, pwm_val);
        pwm_val = brightness_sequence[(i + 7) % sizeof(brightness_sequence)];
        set_led_brightness(1, 4, pwm_val);
        set_led_brightness(2, 3, pwm_val);
        set_led_brightness(3, 2, pwm_val);
        set_led_brightness(4, 2, pwm_val);
        set_led_brightness(5, 4, pwm_val);
        set_led_brightness(1, 8, pwm_val);
        set_led_brightness(6, 6, pwm_val);
        set_led_brightness(6, 7, pwm_val);
        run_pwm_cycle();
        set_led_brightness(7, 4, pwm_val);
        pwm_val = brightness_sequence[(i + 6) % sizeof(brightness_sequence)];
        set_led_brightness(0, 4, pwm_val);
        set_led_brightness(1, 3, pwm_val);
        set_led_brightness(2, 2, pwm_val);
        set_led_brightness(5, 7, pwm_val);
        set_led_brightness(0, 8, pwm_val);
        set_led_brightness(6, 8, pwm_val);
        set_led_brightness(7, 5, pwm_val);
        pwm_val = brightness_sequence[(i + 5) % sizeof(brightness_sequence)];
        set_led_brightness(1, 2, pwm_val);
        set_led_brightness(3, 1, pwm_val);
        set_led_brightness(4, 1, pwm_val);
        set_led_brightness(8, 2, pwm_val);
        set_led_brightness(7, 6, pwm_val);
        pwm_val = brightness_sequence[(i + 4) % sizeof(brightness_sequence)];
        set_led_brightness(0, 3, pwm_val);
        set_led_brightness(2, 1, pwm_val);
        set_led_brightness(2, 8, pwm_val);
        set_led_brightness(3, 8, pwm_val);
        set_led_brightness(7, 7, pwm_val);
        pwm_val = brightness_sequence[(i + 3) % sizeof(brightness_sequence)];
        set_led_brightness(0, 2, pwm_val);
        set_led_brightness(1, 1, pwm_val);
        set_led_brightness(3, 0, pwm_val);
        set_led_brightness(4, 0, pwm_val);
        set_led_brightness(4, 8, pwm_val);
        set_led_brightness(5, 8, pwm_val);
        set_led_brightness(7, 8, pwm_val);
        run_pwm_cycle();
        pwm_val = brightness_sequence[(i + 2) % sizeof(brightness_sequence)];
        set_led_brightness(0, 1, pwm_val);
        set_led_brightness(2, 0, pwm_val);
        pwm_val = brightness_sequence[(i + 1) % sizeof(brightness_sequence)];
        set_led_brightness(1, 0, pwm_val);
        pwm_val = brightness_sequence[(i + 0) % sizeof(brightness_sequence)];
        set_led_brightness(0, 0, pwm_val);

        update_pwm_pattern();
    }
}
